name: CML Training
on: [workflow_dispatch,push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |          
          pip install -r requirements.txt
          
          cml ci

          if [ $GITHUB_REF = refs/heads/main ]; then
            PREVIOUS_REF=HEAD~1
          else
            PREVIOUS_REF=main
          fi

          GITHUB_BRANCH=${GITHUB_REF#refs/heads/}
          
          dvc pull dataset
          dvc repro

          git add . 
          
          git commit -m "Running experiment"
          
          git push origin $GITHUB_BRANCH
          
          dvc push
