name: CML Training
on: [workflow_dispatch,push]
jobs:
  train:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |          
          pip install -r requirements.txt
          
          cml ci

          if [ $GITHUB_REF = refs/heads/main ]; then
            PREVIOUS_REF=HEAD~1
          else
            PREVIOUS_REF=main
          fi

          GITHUB_BRANCH=${GITHUB_REF#refs/heads/}
          
          dvc pull dataset
          dvc repro

          git add . 
          
          git commit -m "Running experiment"
          
          git push origin $GITHUB_BRANCH
          
          dvc push
  report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    needs: train
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Generate report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |

          cml ci

          if [ $GITHUB_REF = refs/heads/main ]; then
            PREVIOUS_REF=HEAD~1
          else
            PREVIOUS_REF=main
          fi

          git fetch --prune

          echo "# CML Report" > report.md
          
          echo "## Plots" >> report.md
          
          echo "### Loss" >> report.md
          echo "#### Training" >> report.md
          dvc plots diff $PREVIOUS_REF workspace --show-vega --targets dvclive/scalars/train/loss.tsv > vega.json
          vl2svg vega.json loss.svg
          cml publish loss.svg --title "Training Loss" --md >> report.md
          
          echo "#### Validation" >> report.md
          dvc plots diff $PREVIOUS_REF workspace --show-vega --targets dvclive/scalars/eval/loss.tsv > vega.json
          vl2svg vega.json val_loss.svg
          cml publish val_loss.svg --title "Validation Loss" --md >> report.md
          
          echo "### Accuracy" >> report.md
          echo "#### Training" >> report.md
          dvc plots diff $PREVIOUS_REF workspace --show-vega --targets dvclive/scalars/train/acc.tsv > vega.json
          vl2svg vega.json acc.svg
          cml publish acc.svg --title "Training Accuracy" --md >> report.md

          echo "#### Validation" >> report.md
          dvc plots diff $PREVIOUS_REF workspace --show-vega --targets dvclive/scalars/eval/acc.tsv > vega.json
          vl2svg vega.json val_acc.svg
          cml publish val_acc.svg --title "Validation Accuracy" --md >> report.md

          echo "## Metrics and Params" >> report.md
          echo "### $PREVIOUS_REF → workspace" >> report.md
          dvc exp diff $PREVIOUS_REF --show-md >> report.md
          cml send-comment report.md
