name: CML
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          dvc pull dataset
          dvc repro
          echo "dvc repro OK"
          
          git fetch --prune
          echo "fetch prune"
          
          dvc metrics diff --show-md main >> report.md
          echo "dvc metrics diff"
          
          dvc plots diff --target dvclive/scalars/loss.tsv --show-vega main > vega.json
          echo "plots diff"
          
          vl2png vega.json | cml publish --md >> report.md
          echo "vl2png"
          
          dvc push dataset --run-cache
          echo "push"
          
          cml send-comment report.md
          echo "send comment"
